[package]
name = "ray_tarcing_in_one_weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
rayon = "1.7.0"
fastrand = "1.9.0"
indicatif = "0.17.3"